server:
  port: 8081
  servlet:
    context-path: /crm
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
#    配置资源访问路径
  web:
    resources:
      static-locations: classpath:/static/, classpath:/templates/
# thymeleaf基本配置
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  分页插件
pagehelper:
  reasonable: true
  helper-dialect: mysql